
help:  ## Show help
	@grep -E '^[.a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | awk 'BEGIN {FS = ":.*?## "}; {printf "\033[36m%-30s\033[0m %s\n", $$1, $$2}'

clean: ## Clean autogenerated files
	rm -rf dist
	find . -type f -name "*.DS_Store" -ls -delete
	find . | grep -E "(__pycache__|\.pyc|\.pyo)" | xargs rm -rf
	find . | grep -E ".pytest_cache" | xargs rm -rf
	find . | grep -E ".ipynb_checkpoints" | xargs rm -rf
	rm -f .coverage

clean-logs: ## Clean logs
	rm -rf logs/**

format: ## Run pre-commit hooks
	pre-commit run -a

sync: ## Merge changes from main branch to your current branch
	git pull
	git pull origin main

test: ## Run not slow tests
	pytest -k "not slow"

test-full: ## Run all tests
	pytest

.PHONY: plots
plots: ## --- Plotting Commands ---

plot-ill-conditioning: plots ## Plot ill-conditioning results
	python scripts/plot_ill_conditioning.py

plot-hessian-condition: plots ## Plot activity Hessian condition number heatmap
	python scripts/plot_hessian_condition.py

.PHONY: train
train: ## Train the model
	python src/train.py

install: ## Install dependencies with uv
	uv sync

install-dev: ## Install development dependencies
	uv sync --extra dev
