# @package model.net.solver.strategy
defaults:
  - activation: p3ots
_target_: src.core.eqprop.strategy.NewtonStrategy
clip_threshold: 0.5
amp_factor: ${model.net.solver.amp_factor}
eps: 1e-6
max_iter: 40
atol: 1e-7
activation: ???
add_nonlin_last: false
momentum: 0.1
attn_factor: 0.8
