# @package model.net.solver.strategy
defaults:
  - activation: ideal
_target_: src.core.eqprop.strategy.ResistiveNetworkStrategy
amp_factor: ${model.net.solver.amp_factor}
add_nonlin_last: false
update_mode: asynchronous
num_iterations: 60
initialization: zero #zero # Options: 'linear', 'zero', 'random'
