# @package model
_target_: src._eqprop.EqPropLitModule
num_classes: 2
compile: false

defaults:
  - optimizer: sgd
  - net: eqprop_xor_onehot_direct

net: ${model.net}

param_adjuster:
  _target_: src.utils.eqprop_utils.AdjustParams
  L: 1e-7
  clamp: true
  normalize: false

scheduler: null
