# @package model
_target_: src._eqprop.EqPropBinaryLitModule
num_classes: 1
compile: false

defaults:
  - optimizer: sgd
  - net: eqprop_xor_direct
param_adjuster:
  _target_: src.utils.eqprop_utils.AdjustParams
  L: 1e-7
  clamp: true
  normalize: false

scheduler: null
