_target_: src.models.mnist_module.MNISTLitModule

defaults:
  - _self_
  - net: mnist
  - optimizer: adam

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

# compile model for faster training with pytorch 2.0
compile: false
