# @package model
_target_: src.models.classifier_module.ClassifierLitModule

defaults:
  - optimizer: sgd
  - net: xor-onehot
  - gradient_hook: low_rank

scheduler: null
num_classes: 2
compile: false
