# @package model
_target_: src.models.classifier_module.BinaryClassifierLitModule

defaults:
  - optimizer: sgd
  - net: xor
  - gradient_hook: low_rank

scheduler: null
num_classes: 1
compile: false
