# @package model.net
defaults:
  - /eqprop/solver: default
  - /eqprop/solver/strategy: resistive 
_target_: src._eqprop.EqPropBackbone
beta: 0.1
bias: true
scale_input: 2
scale_output: 2
cfg: ???

param_adjuster:
  _target_: src.utils.eqprop_utils.AdjustParams

residual: true # Add this line for residual control
res_scale: 0