# @package model.net
defaults:
  - /eqprop/solver: default
  - /eqprop/solver/strategy: resistive
  - initialization: mup
  - _self_

_target_: src._eqprop.EqPropBackbone
beta: 1.5
bias: false
scale_input: 2
scale_output: 2
data_scale: 100
cfg: ???


param_adjuster:
  _target_: src.utils.eqprop_utils.AdjustParams

#residual: false # Add this line for residual control
#res_scale: 4
#layer_scale: 1