# @package model.net
# DirectBackboneConfig - Base config for AnalogEP2
_target_: src._eqprop.AnalogEP2
batch_size: ${data.batch_size}
beta: 0.01
bias: false
positive_w: true
min_w: 1e-6
max_w_gain: 0.08
scale_input: 2
scale_output: 2
cfg: ???

solver:
  _target_: src.core.eqprop.solvers.AnalogEqPropSolver
  amp_factor: 1.0
  beta: ${..beta}
  strategy:
    _target_: src.core.eqprop.strategy.ProxQPStrategy
    amp_factor: ${...solver.amp_factor}
    add_nonlin_last: false
    num_threads: null
    activation:
      _target_: src.core.eqprop.activation.IdealRectifier
      Vl: 0.1
      Vr: 0.9
