# @package model.net
_target_: src._eqprop.EqPropBackbone
beta: 0.1
bias: false
scale_input: 2
scale_output: 2
cfg:
  - 1568  # 784 * 2
  - 128
  - 20    # 10 * 2

solver:
  _target_: src.core.eqprop.solvers.AnalogEqPropSolver
  amp_factor: 1.0
  beta: 0.1
  strategy:
    _target_: src.core.eqprop.strategy.strategies.ProxQPStrategy

param_adjuster:
  _target_: src.utils.eqprop_utils.AdjustParams
